# Generated by Django 2.2.1 on 2020-09-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='colage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('hours', models.CharField(blank=True, max_length=50)),
                ('totalDegree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('student_colage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.colage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentDegree', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_courses',
            field=models.ManyToManyField(through='online_manage.StudentCourses', to='online_manage.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='phoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('user_PhoneNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('doctor_colage', models.ManyToManyField(to='online_manage.colage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='colage',
            name='colage_courses',
            field=models.ManyToManyField(to='online_manage.courses'),
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='assignments/')),
                ('dueTime', models.DateTimeField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('totalDegree', models.IntegerField(blank=True, null=True)),
                ('assignment_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.doctor')),
            ],
        ),
    ]
