# Generated by Django 2.2.1 on 2020-09-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_manage.courses'),
            preserve_default=False,
        ),
    ]
