# Generated by Django 2.2.1 on 2020-09-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0003_auto_20200904_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAssignmentAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.FileField(upload_to='assignmentsAnswers/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_manage.student')),
            ],
        ),
    ]
