# Generated by Django 2.2.1 on 2020-09-08 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0005_auto_20200907_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='vedio',
        ),
        migrations.AddField(
            model_name='lectures',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='lecturesVideo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'ogg', 'mov', 'flv', 'm4v', 'm4p', 'mpg', 'wmv', 'swf'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentassignmentmark',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online_manage.assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignmentmark',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online_manage.student'),
        ),
    ]
