# Generated by Django 2.2.1 on 2020-09-08 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0006_auto_20200908_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='video',
            field=models.FileField(upload_to='lecturesVideo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'ogg', 'mov', 'flv', 'm4v', 'm4p', 'mpg', 'wmv', 'swf', 'mkv'])]),
        ),
    ]
