# Generated by Django 2.2.1 on 2020-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0007_auto_20200908_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentanswers',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='studentAssignmentMark',
        ),
    ]
