# Generated by Django 2.2.1 on 2020-09-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0008_auto_20200908_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_courses',
        ),
        migrations.DeleteModel(
            name='StudentCourses',
        ),
    ]
