# Generated by Django 2.2.1 on 2020-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0009_auto_20200913_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
