# Generated by Django 2.2.1 on 2020-10-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0011_auto_20201007_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
