# Generated by Django 2.2.1 on 2020-11-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_manage', '0012_auto_20201030_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentAssignmentAnswers',
        ),
    ]
